### ISSUE TITLE
Roadmap version 1.0

### ISSUE THREAD

**Issue by hanneskod** [byrokrat/banking#5]
- [x] Make parser smarter, #4 
- [x] Add account numbers for major banks, #2 
- [x] Handle swedbank clearing checkdigit, #1 
- [x] Ignore spaces in account number format (eg "123 456" == "123456")
